### ISSUE TITLE
openvpn is known to have performance issues

### ISSUE THREAD

**Issue by zoobab** [labriqueinternet/vpnclient_ynh#15]
openvpn is known to have performance issues, especially with openssl as a backend lib.

You should consider using elliptic curve based vpn, which is lighter cpu-wise and faster in throughput.

I made some perf tests with curvetun (netsniff-ng), and the speed with encryption is the same as the openvpn speed without encryption. Curvetun also uses some kernel functions that skips parts of the tcpip stack:

"The gain of performance is reached by built-in zero-copy mechanisms, so that on packet reception and transmission the kernel does not need to copy packets from kernel space to user space, and vice versa."

https://github.com/netsniff-ng/netsniff-ng

I had huge respect for openvpn, but I was not so happy when I saw those crappy performances, especially not encrypted.

**Comment by jvaubourg** [comment]
Currently, OpenVPN is probably the most used VPN server. So, using a OpenVPN client increases the compatibility. Maybe we will change this choice later, but not for now, sorry.
