### ISSUE TITLE
Error: Configuration updated but service reload failed / tls-auth missing

### ISSUE THREAD

**Issue by finster-** [labriqueinternet/vpnclient_ynh#21]
Add support for the "ta.key"...

**Comment by jvaubourg** [comment]
What?

**Comment by jvaubourg** [comment]
I don't understand why I can't choose an "incomplete" (rather than "invalid") label for this issue o_^.

**Comment by sbadia** [comment]
:smiley:

**Comment by finster-** [comment]
As you can see [here] (https://raw.githubusercontent.com/labriqueinternet/vpnclient_ynh/master/screenshot.png) you can upload the  
```
ca.crt
client.key
client.crt
```
but for my vpn service i need to use the 
```
ta.key
```
so i asked if it's going to be implemented... :)

**Comment by sbadia** [comment]
@finster- you can switch the vpnclient interface in `expert mode` and add the option by editing the template. (and in the same time copy you tls-auth key on you cube).

`tls-auth ta.key`

We take a look to add this in the web interface, but do not hesitate if you want to send us a pull-request ;-)

**Comment by jvaubourg** [comment]
Fixed by d1d4ac7358054b7052de2c235ba1db0398374df2

You now have an optional field "Upload Shared-Secret" for the ta.key.

Is it okay for you?
