### ISSUE TITLE
404 Not Found right after install

### ISSUE THREAD

**Issue by stevenroose** [labriqueinternet/vpnclient_ynh#27]
I installed the vpnclient app just seconds ago and the given domain+path option (clicked through from the YunoHost dashboard) gives a 404.

This is what the nginx error log says:
`2015/10/08 02:18:36 [error] 9407#0: *14359 "/usr/share/nginx/html/vpnadmin/index.html" is not found (2: No such file or directory), client: 193.190.253.144, server: yuno.roose.ch, request: "GET /vpnadmin/ HTTP/1.1", host: "yuno.roose.ch"`

**Comment by jvaubourg** [comment]
Wow. Could you remove and reinstall VPN Client in command line?

```
yunohost app remove vpnclient
yunohost app install https://github.com/labriqueinternet/vpnclient_ynh
```

Then copy-paste the output here, if you have the same problem.

**Comment by stevenroose** [comment]
Will do tomorrow!

**Comment by stevenroose** [comment]
Got delayed a bit. It works now, thansk!
