### ISSUE TITLE
CSRF on VPN configuration endpoint

### ISSUE THREAD

**Issue by randomstuff** [labriqueinternet/vpnclient_ynh#43]
The VPN configuration endpointt (`/vpnadmin/?/settings`) is vulnerable to CSRF.

**Comment by randomstuff** [comment]
See https://github.com/sofadesign/limonade/issues/54

**Comment by randomstuff** [comment]
According to the tests I just did, this seems mitigates by [SameSite=lax](https://caniuse.com/#search=samesite) cookie setting on [latest YunoHost](https://github.com/YunoHost/SSOwat/pull/103). This is not available on all browsers however (but most evergreen browsers seem to be fine).

**Comment by pitchum** [comment]
Fix included in v1.3.0
