### ISSUE TITLE
Missing release tag

### ISSUE THREAD

**Issue by MCMic** [labriqueinternet/vpnclient_ynh#57]
Hello,

Yunohost is proposing an update from 1.3.2 to 1.4.0, but I cannot find either of those in https://github.com/labriqueinternet/vpnclient_ynh/releases

I wanted to double check the changes before applying the update as VPN client update is always a stressful operation.

I found this commit: https://github.com/labriqueinternet/vpnclient_ynh/commit/b64b8cb18c1ad017fd5c2e1fb58d2e04a056693d so I guess only release tags are missing from the git?
Could you add those?

It seems there is a changelog file: https://github.com/labriqueinternet/vpnclient_ynh/blob/master/CHANGES.md but it is not complete either and stops at 1.3.1.

**Comment by keomabrun** [comment]
Hi @MCMic, this is now solved for version 1.4.0 et 1.4.1. Can I close this issue ?

**Comment by MCMic** [comment]
Yep, thanks
