### ISSUE TITLE
Weird behavior of VPN connection

### ISSUE THREAD

**Issue by MCMic** [labriqueinternet/vpnclient_ynh#67]
Hello,

Since a reboot from a powercut (which was the first reboot since my last update of this app), I lose connection to my server after a few minutes.

I can still ping the external IP, but not SSH on it, or contact any HTTP application.

I can SSH just fine through local network, and `ynh-vpnclient status` says everything is fine:
```
~> sudo ynh-vpnclient status
[INFO] Retrieving Yunohost settings...
[ OK ] Settings retrieved
[INFO] Autodetected internet interface: eth0 (last start: eth0)
[INFO] Autodetected IPv6 address for the VPN server: 2a00:5881:4000::3 (last start: 2a00:5881:4000::3)
[INFO] IPv6 delegated prefix found
[INFO] IPv6 address computed from the delegated prefix: 2a00:5881:4008:d00::42
[INFO] No Hotspot app detected
[ OK ] IPv6 address correctly set
[INFO] No native IPv6 detected
[INFO] No IPv6 server route to set
[ OK ] IPv6/IPv4 firewall set
[ OK ] Host DNS correctly set
[ OK ] Openvpn is running
```
Is it expected that it does not mention IPv4? It’s through v4 that I attempt to SSH/HTTP, because I have no v6 through my provider (only through the VPN).

The tunnel seems up:
```
~> ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:1e:90:a0:78:ee brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.10/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::21e:90ff:fea0:78ee/64 scope link
       valid_lft forever preferred_lft forever
8: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
    link/none
    inet 89.234.140.141/25 brd 89.234.140.255 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 2a00:5881:4008:d00::42/128 scope global
       valid_lft forever preferred_lft forever
    inet6 2a00:5881:4008:d00::/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::a049:685d:a639:80bc/64 scope link flags 800
       valid_lft forever preferred_lft forever
```

If I restart the vpn with `sudo ynh-vpnclient restart`, usually it works again for a few minutes, before going into the same broken state.

**Comment by alexAubin** [comment]
>I lose connection to my server after a few minutes.

But then aren't you still able to connect using the local IP v4 ?

**Comment by MCMic** [comment]
Yes, I never lose local connection, it always work, only the external VPN IP stops responding (except to ping)

**Comment by MCMic** [comment]
I’m on an other connection for the week-end and it works fine from here. This connection has IPv6, so I think the only problem is with the external VPN IPv4 address.

Unrelated question: For AAAA record in my DNS setup, I use the /64 address, and yunohost new diagnostic screen detects this as an error and says I should put the /128 in there, is that necessary? What does it change? I think when I setup DNS I tried both and decided to use the /64 for some reason, but I don’t know much about IPv6.

**Comment by MCMic** [comment]
This was related to fail2ban and not vpn client
