### ISSUE TITLE
Wireguard support

### ISSUE THREAD

**Issue by Thatoo** [labriqueinternet/vpnclient_ynh#68]
Would it be possible for this client to manage also wireguard VPN connection?
Offer the option between OpenVPN and Wireguard?

**Comment by SohKa** [comment]
Everything is possible as long as someone does the work. :) 

More seriously, I'm also be interested into supporting Wireguard. I'll have a look when I'll have the time.

**Comment by HyperCriSiS** [comment]
As there is already a Wireguard Yunohost app, would't it make sense to join forces and work on one solution together :-)?

**Comment by alexAubin** [comment]
Too many things different between openvpn and wireguard, if this happens this will be a totally different app
