### ISSUE TITLE
Compliance with systemd

### ISSUE THREAD

**Issue by jvaubourg** [labriqueinternet/vpnclient_ynh#8]
The first release of the Internet Cube should use Debian Jessie. Because we use a sysvinit service, we need to convert it to the systemd format and replace all the "service" commands by "systemctl". Status commands must be replaced by the is-active option.

**Comment by jvaubourg** [comment]
Should be okay from 6ffe098dcc56e3fb81defe9cfef6fac7f02e42b2 (branch "jessie").

We need strong tests before merging (and losing wheezy compatibility).

**Comment by sbadia** [comment]
fixed by #16
